apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: jenkins-backup

  namespace: saif

spec:

  accessModes:

    - ReadWriteOnce  # Assuming RWX if needed change to ReadWriteMany

  resources:

    requests:

      storage: 1Gi

  storageClassName: tkg-rwx-policy-dev
